### ISSUE TITLE
[Feature Request]: preis anzeige

### ISSUE THREAD

**Issue by JovuTV** [LuminaAppsDev/handyshopper#2]
### Beschreibe die gewünschte Lösung

Eine anzeige wo den gesamnten preis der zu Kaufenden Produkten anzeigt das man schon beim erstellen der liste weis wie viel geld man ca braucht

**Comment by LuminaAppsDev** [comment]
Umgesetzt mit https://github.com/LuminaAppsDev/handyshopper/commit/f1da9cc573b4c38dc67215ca22c636b3b8bba779
Wird in nächster Version enthalten sein.
